services:
  plucklog_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plucklog_fastapi
    restart: always
    # APONTAMENTO EXATO: pasta fastapi_app, arquivo main, variável app
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - PYTHONPATH=${PYTHONPATH}
      - PLUCKLOG_ENV=${PLUCKLOG_ENV}
    ports:
      - "8000:8000"

  plucklog_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plucklog_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PLUCKLOG_ENV=${PLUCKLOG_ENV}

    ports:
      - "3000:3000"
